### ISSUE TITLE
[BUG] Changing the Name and/or Game ID of wad renders the channel read as unknown.

### ISSUE THREAD

**Issue by md500** [Admentus64/Patcher64Plus-Tool#69]
**Description**

I'm trying to inject the rom with the name and game id customized to the wad, but when i install it to the wii (Dolphin) it doesnt appear on System Menu and in Channel on Data Management it shows the channel as Unknown.

**How to Reproduce**

1. Set Current Game Mode to Free Game Selection
2. Select a wad.
3. Select a rom to inject.
4. Enable Custom Channel Tittle and GameID
5. (Optional) Select Patch Options

![image](https://user-images.githubusercontent.com/3111925/230580952-47ba3ee3-36df-4532-bd84-b440aeb2820d.png)

(Virtual Mode: Emunand)
6. Open Dolphin and install the wad file.
7. Load the Wii System Menu 4.3 (You can create this using Modmii and paste the nand files to %APPDATA%\Dolphin Emulator\Wii)

(Normal Mode)
6. Install the wad file to the wii.

8.Issue Triggered:
![image](https://user-images.githubusercontent.com/3111925/230582281-9b68b9dc-e196-457b-8d0f-e2c24d3fe632.png)
![image](https://user-images.githubusercontent.com/3111925/230582350-89bc5ae8-737c-4f15-8feb-807949edf67f.png)
![image](https://user-images.githubusercontent.com/3111925/230582413-a5d18272-1936-4f51-995b-c3bf4975102d.png)

**Expected behavior**

The channel must be shown on System Menu.

![image](https://user-images.githubusercontent.com/3111925/230579601-b010d5df-1731-4794-a190-ee74e5bfc69a.png)
![image](https://user-images.githubusercontent.com/3111925/230579771-be1f74a2-a7fe-407f-b663-c34edcbac4a3.png)

I had to use ShowMiiWads as workaround to acomplish this:
![image](https://user-images.githubusercontent.com/3111925/230582940-1f769ab5-a3af-44e5-b177-9542e172c351.png)
![image](https://user-images.githubusercontent.com/3111925/230585285-430be54e-1d56-4c3a-b917-89cddada03ad.png)
![image](https://user-images.githubusercontent.com/3111925/230583367-7300a699-829e-4d4e-99f7-1bf97fb8d792.png)

**Screenshots**

Screens are in the corresponding context.

**Log files**
[2023-04-07.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/11177567/2023-04-07.log)

**Comment by Admentus64** [comment]
Don't enable channel title changes through the patcher.

**Comment by md500** [comment]
> Don't enable channel title changes through the patcher.

Thanks. In which cases can that option be used?

**Comment by Admentus64** [comment]
It's used for generating alternate save slots for example, useful for Dolphin which has no issue with it.

That way you could have separate save data for regular OoT, or a ROM hack. It's also for Redux which needs it's own set of AR / Gecko Codes. But, as of recently this has been less of an issue since these AR / Gecko Codes are being moved into Redux itself.

Actual Wii Hardware doesn't like messing with the Channel Title and GameID.

**Comment by Admentus64** [comment]
Btw, I intentionally left out patching support for The Sealed Palace in Wii VC mode because it was known to have issues.

**Comment by md500** [comment]
> It's used for generating alternate save slots for example, useful for Dolphin which has no issue with it.
> 
> That way you could have separate save data for regular OoT, or a ROM hack. It's also for Redux which needs it's own set of AR / Gecko Codes. But, as of recently this has been less of an issue since these AR / Gecko Codes are being moved into Redux itself.
> 
> Actual Wii Hardware doesn't like messing with the Channel Title and GameID.

Mmm, i tried with a preset like "Missing Link" but it occurs the same issue. Seems that patcher64+ apply the Channel Title and GameID Even though the option is unchecked. This issue doesnt happen if i use ShowMiiWads (on the video you can see it: https://youtu.be/kwUvdc068es ). About Sealed Palace, is solved on the latest patch (1.21 patch) 3 days ago.

**Comment by Admentus64** [comment]
Issue still can't be accepted.

Like I said, the use of external tools and Free Mode patching invalidated this bug report.

Open a new issue instead with the proper info.
